// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JwtTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "JwtTools.b881ac88-93df-401b-9ff7-03b5d3800e5c";
        public const string Name = "JwtTools";
        public const string Description = @"A tool window to help with JWT token decoding and other things.";
        public const string Language = "en-US";
        public const string Version = "0.2";
        public const string Author = "Tim Heuer";
        public const string Tags = "aspnet, jwt, identity";
    }
}
